name: Build with Bun

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 安装Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 安装依赖
        run: bun install

      - name: 构建项目
        run: bun run build

      - name: 压缩构建产物
        run: zip -r dist.zip dist

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist.zip
